CUDA_VISIBLE_DEVICES=2 python ./src/train_bash.py \
    --stage sft \
    --do_train \
    --model_name_or_path /datas/huggingface/chatglm3-6b/ \
    --dataset test \
    --template default \
    --finetuning_type lora \
    --lora_target query_key_value \
    --output_dir ./output \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 5 \
    --save_steps 25 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --fp16